name: Build NVGT Program

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download NVGT for Windows
        run: |
          curl -L -o nvgt_installer.exe https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.exe

      - name: Install NVGT
        run: |
          Start-Process -FilePath "nvgt_installer.exe" -ArgumentList "/silent" -Wait
          $env:PATH += ";C:\nvgt"

      - name: Compile GetNVGT
        run: |
          C:\nvgt\nvgt.exe -c -q get.nvgt
        continue-on-error: false

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: GetNVGT-windows
          path: GetNVGT.zip

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Setup NVGT for Linux
        run: |
          wget -q https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.tar.gz
          tar -xzf nvgt_0.90.0_dev.tar.gz -C $HOME
          chmod +x $HOME/nvgt

      - name: Compile GetNVGT
        run: |
          export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
          $HOME/nvgt -c -q get.nvgt
        continue-on-error: false

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: GetNVGT-linux
          path: GetNVGT.zip

  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Install NVGT for macOS
        run: |
          wget -q https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.dmg
          hdiutil attach nvgt_0.90.0_dev.dmg
          sudo cp -R /Volumes/NVGT/nvgt.app /Applications/ || sudo cp -R /Volumes/*/nvgt.app /Applications/
          hdiutil detach /Volumes/NVGT || hdiutil detach /Volumes/nvgt* || true

      - name: Compile GetNVGT
        run: |
          /Applications/nvgt.app/Contents/MacOS/nvgt -c -q get.nvgt
        continue-on-error: false

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: GetNVGT-macos
          path: GetNVGT.dmg

  release:
    name: Create Latest Release
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete existing latest release
        run: |
          gh release delete latest --yes || echo "No existing release to delete"
          git push origin :refs/tags/latest || echo "No existing tag to delete"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Rename artifacts for release
        run: |
          mv artifacts/GetNVGT-windows/GetNVGT.zip GetNVGT-windows.zip
          mv artifacts/GetNVGT-linux/GetNVGT.zip GetNVGT-linux.zip
          mv artifacts/GetNVGT-macos/GetNVGT.dmg GetNVGT-macos.dmg

      - name: Create Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Development Build
          body: |
            Automated build from the latest commit on main branch.

            **Commit:** ${{ github.sha }}
            **Date:** ${{ github.event.head_commit.timestamp }}

            Download the appropriate version for your platform:
            - **Windows:** GetNVGT-windows.zip
            - **Linux:** GetNVGT-linux.zip
            - **macOS:** GetNVGT-macos.dmg
          prerelease: true
          files: |
            GetNVGT-windows.zip
            GetNVGT-linux.zip
            GetNVGT-macos.dmg
