name: Build NVGT Program

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download NVGT for Windows
        run: |
          curl -L -o nvgt_installer.exe https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.exe

      - name: Install NVGT
        run: |
          Start-Process -FilePath "nvgt_installer.exe" -ArgumentList "/silent" -Wait
          $env:PATH += ";C:\nvgt"

      - name: Compile GetNVGT
        run: |
          C:\nvgt\nvgt.exe -c -q get.nvgt
        continue-on-error: false

      - name: Extract contents (avoid double-zip)
        run: |
          Expand-Archive -Path GetNVGT.zip -DestinationPath GetNVGT-windows -Force

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: GetNVGT-windows
          path: GetNVGT-windows/

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Setup NVGT for Linux
        run: |
          wget -q https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.tar.gz
          tar -xzf nvgt_0.90.0_dev.tar.gz -C $HOME
          chmod +x $HOME/nvgt

      - name: Compile GetNVGT
        run: |
          export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
          $HOME/nvgt -c -q get.nvgt
        continue-on-error: false

      - name: Extract contents (avoid double-zip)
        run: |
          unzip -q GetNVGT.zip -d GetNVGT-linux

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: GetNVGT-linux
          path: GetNVGT-linux/

  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Install NVGT for macOS
        run: |
          wget -q https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.dmg
          hdiutil attach nvgt_0.90.0_dev.dmg
          sudo cp -R /Volumes/NVGT/nvgt.app /Applications/ || sudo cp -R /Volumes/*/nvgt.app /Applications/
          hdiutil detach /Volumes/NVGT || hdiutil detach /Volumes/nvgt* || true

      - name: Compile GetNVGT
        run: |
          /Applications/nvgt.app/Contents/MacOS/nvgt -c -q get.nvgt
        continue-on-error: false

      - name: Extract DMG contents (avoid nested packaging)
        run: |
          hdiutil attach GetNVGT.dmg -mountpoint /Volumes/GetNVGT
          mkdir GetNVGT-macos
          cp -R /Volumes/GetNVGT/* GetNVGT-macos/
          hdiutil detach /Volumes/GetNVGT

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: GetNVGT-macos
          path: GetNVGT-macos/

  release:
    name: Create Latest Release
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Package artifacts for release
        run: |
          cd artifacts/GetNVGT-windows && zip -r ../../GetNVGT-windows.zip * && cd ../..
          cd artifacts/GetNVGT-linux && zip -r ../../GetNVGT-linux.zip * && cd ../..
          cd artifacts/GetNVGT-macos && zip -r ../../GetNVGT-macos.zip * && cd ../..

      - name: Create or Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Development Build
          body: |
            Automated build from the latest commit on main branch.

            **Commit:** ${{ github.sha }}
            **Date:** ${{ github.event.head_commit.timestamp }}

            Download the appropriate version for your platform:
            - **Windows:** GetNVGT-windows.zip
            - **Linux:** GetNVGT-linux.zip
            - **macOS:** GetNVGT-macos.zip
          prerelease: true
          files: |
            GetNVGT-windows.zip
            GetNVGT-linux.zip
            GetNVGT-macos.zip
